[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080
# This defines the address, bnv-manager is available for users.
# E.g.: https://manager.example.com or http://manager.example.com:8080
PublicURI = ""
# Add each host / domain this server should be accessed by.
# In scheme: https://manager.example.com
AllowedHosts = [
    "",
]
# You can set this to true, if bnv-manager is deployed behin a reverse proxy
# and therefore has no TLS configured. You can still set your AllowedHosts
# to enforce the use of https:// and add the X-Forwarded-Proto header on
# your reverse proxy.
UseForwardedProtoHeader = true

[Database]
# Must be one of [sqlite, mysql, postgresql]
# In case of sqlite only Driver and Name are required.
Driver = ""
# Name specifies the name of the database or the path of the file in case of sqlite.
#
# sqlite specific:
#   You can specify either an absolute or relative path.
#   If a relative path is used, the WorkingDirectory setting from the service file applies.
Name = ""
# The following setting only apply if Driver is one of [mysql, postgresql]
Host = ""
Port = 0
User = ""
Password = ""
