[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080
# This defines the address, bnv-manager is available for users.
# E.g.: https://manager.example.com or http://manager.example.com:8080
PublicURI = ""
# Add each host / domain this server should be accessed by.
# In scheme: https://manager.example.com
AllowedHosts = [
    "",
]
# You can set this to true, if bnv-manager is deployed behin a reverse proxy
# and therefore has no TLS configured. You can still set your AllowedHosts
# to enforce the use of https:// and add the X-Forwarded-Proto header on
# your reverse proxy.
UseForwardedProtoHeader = true

[Database]
# Must be one of [sqlite, mysql, postgresql]
# In case of sqlite only Driver and Name are required.
Driver = ""
# Name specifies the name of the database or the path of the file in case of sqlite.
#
# sqlite specific:
#   You can specify either an absolute or relative path.
#   If a relative path is used, the WorkingDirectory setting from the service file applies.
Name = ""
# The following setting only apply if Driver is one of [mysql, postgresql]
Host = ""
Port = 0
User = ""
Password = ""

[LDAP]
# Specify the LDAP server uri, e.g. ldaps://ldap.example.com
ServerURI = ""
# As bnv-manager must have access to the hashed password in LDAP,
# make sure to bind a user with the permission to retrieve the passwords.
#
# It is only used to synchronize the passwords to mailcow
AdminBindUser = ""
AdminBindPassword = ""
# The read-only user is used for querying users for login
ROBindUser = ""
ROBindPassword = ""
UserSearchBase = ""
# Normal LDAP filter. Use %s to insert the username.
UserSearchFilter = "(&(objectClass=inetOrgPerson)(uid=%s))"
ClubSearchBase = ""
# Normal LDAP filter. Use %s to insert the club abbreviation.
ClubSearchFilter = "(&(objectClass=groupOfNames)(cn=%s))"
# The group to query to check if the user is a club admin
ClubAdminGroupDN = ""
DomainSearchBase = ""
# Normal LDAP filter. Use %s to insert the domain.
DomainSearchFilter = "(&(objectClass=domain)(dc=%s))"
# The group to query to check if the user is an admin
AdminGroupDN = ""
# A dummy user that must not be included in the search base of any of the above search bases
DummyUserDN = ""

[Mailcow]
ServerURI = ""
APIKey = ""