# Generated by Django 3.1.7 on 2021-02-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedgroup',
            old_name='model',
            new_name='group',
        ),
    ]
