# Generated by Django 3.2.9 on 2021-12-12 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\w+$')]),
        ),
    ]
