# Generated by Django 3.2.9 on 2021-12-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_club_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
