# Generated by Django 3.1.7 on 2021-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20210228_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='associated_clubs',
            field=models.ManyToManyField(to='generic.AdvancedGroup'),
        ),
    ]
