# Generated by Django 3.2.9 on 2021-12-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_alter_club_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='associated_managers',
        ),
    ]
