# Generated by Django 3.1.7 on 2021-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_advanceduser_associated_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='associated_clubs',
            field=models.ManyToManyField(blank=True, to='generic.AdvancedGroup'),
        ),
    ]
