# Generated by Django 3.2.9 on 2021-12-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_remove_club_associated_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='associated_domains',
            field=models.ManyToManyField(blank=True, to='generic.Domain'),
        ),
    ]
