# Generated by Django 3.2.9 on 2021-12-12 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20211212_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(default='', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
